### ISSUE TITLE
Add option to make one-line exception for getters

### ISSUE THREAD

**Issue by devinivy** [hapijs/rule-scope-start#5]
The impetus for this rule is to have a blank line to denote that an asynchronous function call might occur.  One case in which it's guaranteed that there's no async business is in a getter.  It would be very convenient, in particular for static class getters, to have an option to allow one-liners there.

Here's an example,
```js
// Allowed
const MyClass = class {
    static get name() {
        return 'MySpecialClass';
    }
};

// Allowed
const MyClass = class {
    static get name() { return 'MySpecialClass'; }
};

// Still not allowed
const fn = function () {
    return 'someValue';
};
```

**Comment by cjihrig** [comment]
I don't have a problem with this personally. Can you raise this on the hapi style guide though to make sure Eran and everyone else is fine with it.

**Comment by devinivy** [comment]
Can do!  Wouldn't necessarily have to change the hapi style guide if we make this an additional one-liner option, but I wouldn't mind it in the official hapi style guide either.

**Comment by hueniverse** [comment]
Closing due to lack of progress.
